#Spring cloud config configurations
spring:
  cloud:
    config:
      uri: http://localhost:8080
#Spring jpa configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
#Spring datasource configurations
  datasource:
    url: "jdbc:mysql://localhost:3306/bookdb?useSSL=false"
    driver-class-name: "com.mysql.jdbc.Driver"
    username: root
    password: password
    
# Eureka Client confiigurations
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
 